required-version = "==0.16.9"
target-version = "py311"
line-length = 88
extend-exclude = ["./server", "./run", "bin", ".tools", "servers/files", "packs/huds", "packs/vendor"]

[format]
quote-style = "double"
indent-style = "space"
line-ending = "lf"
